### ISSUE TITLE
unable to open in localhost

### ISSUE THREAD

**Issue by shikhalakra22** [PiyushPawar17/classroom#1]
![Screenshot from 2020-10-07 22-49-41](https://user-images.githubusercontent.com/48185254/95365502-d5aca700-08ef-11eb-816c-82e03d84a2be.png)

I am getting this error can you provide me the procedure on how to setup the firebase. Can you please resolve this issue.

**Comment by piyush-pawar-17** [comment]
@shikhalakra22 Hey! Sorry for the late reply. You can find steps to setup firebase [here](https://firebase.google.com/docs/web/setup). You can change the imports from `./firebase` to `./firebase/firebase`. to resolve the issue

**Comment by piyush-pawar-17** [comment]
Let me know if the issue is resolved
